BEGIN;
DROP TRIGGER IF EXISTS app_stop_jobs_no_truncate ON app_stop_jobs;
DROP TRIGGER IF EXISTS app_stop_jobs_no_delete ON app_stop_jobs;
DROP TRIGGER IF EXISTS deployment_events_no_truncate ON deployment_events;
DROP TRIGGER IF EXISTS deployment_events_no_update_delete ON deployment_events;
DROP TRIGGER IF EXISTS deployment_jobs_no_truncate ON deployment_jobs;
DROP TRIGGER IF EXISTS deployment_jobs_no_delete ON deployment_jobs;
DROP TRIGGER IF EXISTS app_stop_jobs_integrity_guard ON app_stop_jobs;
DROP TRIGGER IF EXISTS deployment_jobs_integrity_guard ON deployment_jobs;
DROP TRIGGER IF EXISTS app_releases_parentage_guard ON app_releases;
DROP FUNCTION IF EXISTS enforce_app_stop_job_integrity;
DROP FUNCTION IF EXISTS enforce_deployment_job_integrity;
DROP FUNCTION IF EXISTS enforce_app_release_parentage;
DROP FUNCTION IF EXISTS deny_deployment_event_mutation;
DROP FUNCTION IF EXISTS normalize_release_runtime_spec;
DROP INDEX IF EXISTS deployment_jobs_active_app_uidx;
ALTER TABLE deployment_jobs DROP CONSTRAINT IF EXISTS deployment_jobs_attempts_nonnegative_check;
ALTER TABLE deployment_jobs DROP CONSTRAINT IF EXISTS deployment_jobs_idempotency_key_length_check;
COMMIT;
