$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot; Set-Location $Root
$Compose = @('docker','compose'); if ($env:COMPOSE_PROJECT_NAME) { $Compose += @('--project-name',$env:COMPOSE_PROJECT_NAME) }; $Compose += @('--env-file','.env','-f','deploy/compose.yaml'); if ($env:CLOUDMETER_COMPOSE_OVERRIDE) { $Compose += @('-f', $env:CLOUDMETER_COMPOSE_OVERRIDE) }
$port = if ($env:PLATFORM_PORT) {[int]$env:PLATFORM_PORT} else {8080}; $api="http://127.0.0.1:$port/api"
function DB([string]$q) { $v=& $Compose[0] $Compose[1..($Compose.Length-1)] exec -T postgres psql -q -U cloudmeter -d cloudmeter -Atc $q; if($LASTEXITCODE-ne 0){throw 'database query failed'}; (($v|Select-Object -First 1)-as[string]).Trim() }
function Session([string]$uid) { $b=New-Object byte[] 32; $rng=[Security.Cryptography.RandomNumberGenerator]::Create(); try {$rng.GetBytes($b)} finally {$rng.Dispose()}; $t=([Convert]::ToBase64String($b)).TrimEnd('=').Replace('+','-').Replace('/','_'); $id=DB "INSERT INTO sessions(user_id,token_hash,expires_at) VALUES('$uid',digest('$t','sha256'),now()+interval '15 minutes') RETURNING id"; [pscustomobject]@{ID=$id;Token=$t} }
function Wait-DB([string]$q,[string]$expected,[int]$seconds=45) { $deadline=(Get-Date).AddSeconds($seconds); do{$v=DB $q;if($v -eq $expected){return};Start-Sleep -Seconds 2}while((Get-Date)-lt $deadline);throw "timed out waiting for $expected; last value was $v" }
$admin=DB "SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE r.code='super_admin' AND u.status='active' LIMIT 1"; if(!$admin){throw 'active super administrator required'}
$a=Session $admin; $ah=@{Authorization="Bearer $($a.Token)"}; $marker=[guid]::NewGuid().ToString('N').Substring(0,12); $email="plan-credit-$marker@example.invalid"; $password="PlanCredit-$marker-Password!"; $planCode="verify-credit-$marker"
try {
  $createdUser=Invoke-RestMethod -Method Post "$api/admin/users" -Headers $ah -ContentType 'application/json' -Body (@{email=$email;password=$password;displayName='套餐额度验收';role='user'}|ConvertTo-Json -Compress); $userID=$createdUser.id
  $plan=Invoke-RestMethod -Method Post "$api/admin/plans" -Headers $ah -ContentType 'application/json' -Body (@{code=$planCode;name="额度验收 $marker"}|ConvertTo-Json -Compress)
  $versionBody=@{cyclePriceCents=0;apps=1;cpuCores=1;memoryGiB=1;systemDiskGiB=5;dataDiskGiB=0;backupStorageGiB=0;backupOperationsPerMonth=0;concurrentDeployments=1;publicIngresses=1;ingressOverageEnabled=$false;egressGiB=1;egressOverageEnabled=$false;creditGrantCents=1234;allowedProductIds=@();effectiveAt=(Get-Date).ToUniversalTime().ToString('o')}
  $v1=Invoke-RestMethod -Method Post "$api/admin/plans/$($plan.id)/versions" -Headers $ah -ContentType 'application/json' -Body ($versionBody|ConvertTo-Json -Compress)
  $assignBody=@{planVersionId=$v1.id;endsAt=$null}|ConvertTo-Json -Compress
  Invoke-RestMethod -Method Put "$api/admin/users/$userID/subscription" -Headers $ah -ContentType 'application/json' -Body $assignBody|Out-Null
  Invoke-RestMethod -Method Put "$api/admin/users/$userID/subscription" -Headers $ah -ContentType 'application/json' -Body $assignBody|Out-Null
  $ref="subscription-credit/$userID/"; $count=[int](DB "SELECT count(*) FROM credit_grants WHERE user_id='$userID' AND business_ref LIKE '$ref%'"); $amount=[int64](DB "SELECT coalesce(max(amount_cents),0) FROM credit_grants WHERE user_id='$userID' AND business_ref LIKE '$ref%'"); if($count -ne 1 -or $amount -ne 1234){throw "assignment grant invariant failed: count=$count amount=$amount"}
  $versionBody.creditGrantCents=2345; $v2=Invoke-RestMethod -Method Post "$api/admin/plans/$($plan.id)/versions" -Headers $ah -ContentType 'application/json' -Body ($versionBody|ConvertTo-Json -Compress); $upgrade=Invoke-RestMethod -Method Put "$api/admin/users/$userID/subscription" -Headers $ah -ContentType 'application/json' -Body (@{planVersionId=$v2.id;endsAt=$null}|ConvertTo-Json -Compress); $count2=[int](DB "SELECT count(*) FROM credit_grants WHERE user_id='$userID' AND business_ref LIKE '$ref%'"); $total2=[int64](DB "SELECT coalesce(sum(amount_cents),0) FROM credit_grants WHERE user_id='$userID' AND business_ref LIKE '$ref%'"); if($count2 -ne 2 -or $total2 -ne 2345 -or $upgrade.creditGrantedCents -ne 1111){throw "same-month upgrade did not grant only the difference: count=$count2 total=$total2 delta=$($upgrade.creditGrantedCents)"}
  $downgrade=Invoke-RestMethod -Method Put "$api/admin/users/$userID/subscription" -Headers $ah -ContentType 'application/json' -Body $assignBody; $totalAfterDowngrade=[int64](DB "SELECT coalesce(sum(amount_cents),0) FROM credit_grants WHERE user_id='$userID' AND business_ref LIKE '$ref%'"); if($totalAfterDowngrade -ne 2345 -or $downgrade.creditGrantedCents -ne 0){throw 'same-month downgrade clawed back or reissued credit'}
  $concurrentUser=Invoke-RestMethod -Method Post "$api/admin/users" -Headers $ah -ContentType 'application/json' -Body (@{email="concurrent-credit-$marker@example.invalid";password=$password;displayName='并发额度验收';role='user'}|ConvertTo-Json -Compress); $concurrentID=$concurrentUser.id; $concurrentBody=@{planVersionId=$v2.id;endsAt=$null}|ConvertTo-Json -Compress
  $jobs=1..6|ForEach-Object { Start-Job -ScriptBlock { param($uri,$token,$body) try { (Invoke-WebRequest -UseBasicParsing -Method Put $uri -Headers @{Authorization="Bearer $token"} -ContentType 'application/json' -Body $body).StatusCode } catch { [int]$_.Exception.Response.StatusCode } } -ArgumentList "$api/admin/users/$concurrentID/subscription",$a.Token,$concurrentBody }
  try { $statuses=@($jobs|Wait-Job|Receive-Job); if($statuses.Count-ne 6 -or @($statuses|Where-Object{$_-ne 200}).Count){throw "concurrent subscription requests failed: $($statuses -join ',')"} } finally { $jobs|Remove-Job -Force }
  $concurrentTotal=[int64](DB "SELECT coalesce(sum(amount_cents),0) FROM credit_grants WHERE user_id='$concurrentID' AND business_ref LIKE 'subscription-credit/$concurrentID/%'"); if($concurrentTotal-ne2345){throw "concurrent assignments granted $concurrentTotal cents instead of 2345"}
  $workerUser=Invoke-RestMethod -Method Post "$api/admin/users" -Headers $ah -ContentType 'application/json' -Body (@{email="worker-credit-$marker@example.invalid";password=$password;displayName='Worker额度验收';role='user'}|ConvertTo-Json -Compress); $workerID=$workerUser.id
  DB "UPDATE user_subscriptions SET plan_version_id='$($v2.id)',entitlements_snapshot=(SELECT entitlements FROM plan_versions WHERE id='$($v2.id)'),cycle_price_cents_snapshot=0,status='active',starts_at=now(),ends_at=NULL,grace_ends_at=NULL WHERE user_id='$workerID'"|Out-Null
  Wait-DB "SELECT count(*) FROM credit_grants WHERE user_id='$workerID' AND business_ref LIKE 'subscription-credit/$workerID/%'" '1'
  $workerAudit=[int](DB "SELECT count(*) FROM audit_logs WHERE subject_user_id='$workerID' AND action='subscription.credit_grant'"); if($workerAudit -lt 1){throw 'worker grant audit record missing'}
  $expiryOK=DB "SELECT bool_and(expires_at=(date_trunc('month',now() AT TIME ZONE 'UTC')+interval '1 month') AT TIME ZONE 'UTC') FROM credit_grants WHERE user_id IN ('$userID','$workerID') AND business_ref LIKE 'subscription-credit/%'"; if($expiryOK -ne 't'){throw 'subscription grant expiration is not the next UTC month boundary'}
  Write-Host 'Plan credit entitlement, retry and concurrency idempotency, upgrade difference, downgrade retention and Worker reconciliation verification passed'
} finally { DB "UPDATE sessions SET revoked_at=now() WHERE id='$($a.ID)'"|Out-Null }
