<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue';import {BellRing,Save} from '@lucide/vue';import {api} from '../api';
const form=reactive({enabled:false,thresholdCents:100,cooldownHours:24}),busy=ref(false),message=ref(''),error=ref(''),inviteCode=ref(''),redeemCode=ref('');
onMounted(async()=>{try{Object.assign(form,await api('/settings/balance-alert'))}catch(e){error.value=(e as Error).message}});
async function save(){try{busy.value=true;await api('/settings/balance-alert',{method:'PUT',body:JSON.stringify(form)});message.value='余额提醒设置已保存';error.value=''}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function createInvite(){try{const data=await api<{code:string;rewardCents:number}>('/invites',{method:'POST'});inviteCode.value=data.code;message.value=`邀请码已创建，好友核销后你将获得 ¥${(data.rewardCents/100).toFixed(2)}`}catch(e){error.value=(e as Error).message}}
async function redeemInvite(){try{const data=await api<{rewardCents:number}>('/invites/redeem',{method:'POST',body:JSON.stringify({code:redeemCode.value})});message.value=`核销成功，邀请者已获得 ¥${(data.rewardCents/100).toFixed(2)}`;redeemCode.value=''}catch(e){error.value=(e as Error).message}}
</script>
<template><main class="workspace"><header><div><p class="eyebrow">账户安全</p><h1>余额提醒</h1><p>余额进入临界区间时提醒你，恢复后才会开始下一轮提醒。</p></div></header><p v-if="error" class="message">{{error}}</p><p v-if="message" class="status-ok">{{message}}</p><section class="settings-card"><div class="section-heading"><div><BellRing :size="20"/><h2>低余额通知</h2></div><label class="switch"><input v-model="form.enabled" type="checkbox"/><span/></label></div><form class="form-grid" @submit.prevent="save"><label>提醒阈值（元）<input :value="form.thresholdCents/100" type="number" min="0" step="0.01" @input="form.thresholdCents=Math.round(Number(($event.target as HTMLInputElement).value)*100)"/><small>余额低于或等于此金额时进入低余额状态。</small></label><label>重复提醒冷却（小时）<input v-model.number="form.cooldownHours" type="number" min="1" max="720"/><small>同一轮低余额状态不会高频发送通知。</small></label><button class="primary compact" :disabled="busy"><Save :size="16"/>保存设置</button></form></section><section class="settings-card"><div class="section-heading"><div><h2>邀请奖励</h2><small>奖励金额由管理员设置，并在邀请码创建时固定。</small></div></div><div class="form-grid"><button class="secondary compact" @click="createInvite">生成一次性邀请码</button><label v-if="inviteCode">邀请码<input :value="inviteCode" readonly/></label><form class="inline-form" @submit.prevent="redeemInvite"><label>核销邀请码<input v-model="redeemCode" minlength="24" maxlength="24" required placeholder="输入好友的邀请码"/></label><button class="primary compact">确认核销</button></form></div></section></main></template>
