<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { Activity,ArrowDown,ArrowUp,Cpu,HardDrive,MemoryStick,RefreshCw } from '@lucide/vue'
import { api } from '../api'
type Section={error:string};type Metrics={cpu:Section&{usagePercent:number|null};memory:Section&{totalBytes:number|null;usedBytes:number|null;availableBytes:number|null};disk:Section&{totalBytes:number|null;usedBytes:number|null;availableBytes:number|null};network:Section&{rxBytes:number|null;txBytes:number|null;rxBytesPerSecond:number|null;txBytesPerSecond:number|null};sampledAt:string}
const data=ref<Metrics|null>(null),loading=ref(true),error=ref('');let timer=0
const stale=computed(()=>!data.value||Date.now()-new Date(data.value.sampledAt).getTime()>20000)
function bytes(value:number|null|undefined){if(value==null)return '--';if(value<1024)return value.toFixed(0)+' B';if(value<1024**2)return (value/1024).toFixed(1)+' KiB';if(value<1024**3)return (value/1024**2).toFixed(1)+' MiB';return (value/1024**3).toFixed(2)+' GiB'}
function percent(used:number|null,total:number|null){return used!=null&&total?Math.min(100,used/total*100):0}
async function load(){try{data.value=await api<Metrics>('/admin/host-metrics');error.value=''}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
onMounted(async()=>{await load();timer=window.setInterval(load,5000)});onBeforeUnmount(()=>window.clearInterval(timer))
</script>
<template><main class="workspace metrics-page"><header class="detail-header"><div><p class="eyebrow">基础设施</p><h1>性能监控</h1><p>宿主机资源与 Docker 数据盘，每 5 秒自动刷新。</p></div><button class="secondary compact" :disabled="loading" @click="load"><RefreshCw :class="{spin:loading}" :size="16"/>刷新</button></header><p v-if="error" class="message">{{error}}</p><p v-if="stale&&!loading" class="configuration-status blocked">采样数据已超过 20 秒，Worker 可能暂时不可用。</p><section v-if="loading&&!data" class="host-metric-grid" aria-busy="true"><article v-for="index in 4" :key="index"><span class="skeleton skeleton-text" style="width:96px"></span><span class="skeleton skeleton-title" style="width:70%"></span><span class="skeleton skeleton-text" style="width:50%"></span></article></section><section v-else-if="data" class="host-metric-grid"><article><header><Cpu :size="19"/><span>CPU 使用率</span></header><strong>{{data.cpu.error?'--':Number(data.cpu.usagePercent||0).toFixed(1)+'%'}}</strong><i><em :style="{width:(data.cpu.usagePercent||0)+'%'}"></em></i><small>{{data.cpu.error||'全部宿主机核心的瞬时平均值'}}</small></article><article><header><MemoryStick :size="19"/><span>内存</span></header><strong>{{bytes(data.memory.usedBytes)}} / {{bytes(data.memory.totalBytes)}}</strong><i><em :style="{width:percent(data.memory.usedBytes,data.memory.totalBytes)+'%'}"></em></i><small>{{data.memory.error||'可用 '+bytes(data.memory.availableBytes)}}</small></article><article><header><HardDrive :size="19"/><span>Docker 数据盘</span></header><strong>{{bytes(data.disk.usedBytes)}} / {{bytes(data.disk.totalBytes)}}</strong><i><em :style="{width:percent(data.disk.usedBytes,data.disk.totalBytes)+'%'}"></em></i><small>{{data.disk.error||'剩余 '+bytes(data.disk.availableBytes)}}</small></article><article><header><Activity :size="19"/><span>宿主机网络</span></header><div class="network-rates"><span><ArrowDown :size="16"/>{{bytes(data.network.rxBytesPerSecond)}}/s</span><span><ArrowUp :size="16"/>{{bytes(data.network.txBytesPerSecond)}}/s</span></div><small>{{data.network.error||'累计接收 '+bytes(data.network.rxBytes)+' · 发送 '+bytes(data.network.txBytes)}}</small></article></section><p v-if="data" class="quiet">最近采样：{{new Date(data.sampledAt).toLocaleString('zh-CN')}}</p></main></template>
<style scoped>.metrics-page{display:grid;gap:18px}.host-metric-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.host-metric-grid article{display:grid;gap:13px;padding:18px;border:1px solid var(--border,#ddd);border-radius:16px;background:var(--panel,#fff)}.host-metric-grid header{display:flex;align-items:center;gap:9px;color:var(--text-muted,#666)}.host-metric-grid strong{font-size:26px}.host-metric-grid i{height:7px;border-radius:99px;background:var(--muted,#eee);overflow:hidden}.host-metric-grid i em{display:block;height:100%;border-radius:inherit;background:currentColor;transition:width .35s ease}.host-metric-grid small{color:var(--text-muted,#777)}.network-rates{display:flex;gap:22px;font-size:20px;font-weight:700}.network-rates span{display:flex;align-items:center;gap:6px}@media(max-width:720px){.host-metric-grid{grid-template-columns:1fr}}
</style>
